/* ═══════════════════════════════════════════════════════════
   DADOS DO SITE — produtos, cabazes, preços e fotos

   MODELO DE PREÇO (por produto):
     nome   → nome mostrado
     peso   → quantidade/unidade de venda (ex: "1 kg", "500 g", "1 unidade • aprox. 800 g")
     preco  → preço para essa quantidade (ex: "1,90 €"). É o valor cobrado por cada unidade no carrinho.
     foto   → chave de FOTOS (a imagem)

   VENDA POR PESO APROXIMADO (fruta/legume vendido à unidade mas pesado):
     venda:"estimado", pricePerKg:<n>, averageWeightKg:<n>, (opcional) weightRange:"7–9 kg"
     → o cartão mostra "€/kg"; o carrinho calcula uma ESTIMATIVA (pricePerKg × peso médio).

   PROMOÇÃO:
     promo:true, precoNormal:"1,99 €" (riscado), preco:"0,99 €" (destacado)
     → o carrinho usa `preco` (o preço promocional).

   baseLinha  → linha extra opcional no cartão (ex: "Base: 2,99 €/kg")
   status     → "Indisponível" esconde o botão de compra
   rel        → nomes de produtos relacionados (cross-sell "Também pode gostar")

   COMO ATUALIZAR UM PREÇO:  substituir  preco:P  por  preco:"1,90 €"
   ═══════════════════════════════════════════════════════════ */
  const P = "A consultar";

  const FOTOS = {
    bananas:      "fotos/catalogo/banana-del-monte.webp",
    laranjas:     "fotos/catalogo/laranja-africa-do-sul.webp",
    laranja_algarve: "fotos/catalogo/laranja-algarve.webp",
    laranja_algarve_premium: "fotos/catalogo/laranja-algarve-premium.webp",
    morangos:     "fotos/catalogo/morango-500g.webp",
    melancia:     "fotos/catalogo/melancia-quarto.webp",
    melancia_sementes: "fotos/catalogo/melancia-com-sementes.webp",
    ananas:       "fotos/catalogo/abacaxi-maturado.webp",
    abacaxi_aviao: "fotos/catalogo/abacaxi-aviao-costa-rica.webp",
    pessegos:     "fotos/catalogo/pessego-amarelo-pequeno.webp",
    melao_verde:  "fotos/catalogo/melao.webp",
    melao_branco: "fotos/catalogo/melao.webp",
    melao_am:     "fotos/catalogo/meloa.webp",
    figos:        "fotos/catalogo/figos.webp",
    roma:         "fotos/catalogo/roma.webp",
    tangerina:    "fotos/catalogo/tangerina.webp",
    clementina:   "fotos/catalogo/clementina.webp",
    macas:      "fotos/catalogo/maca-royal-gala-media.webp",
    uvas:       "fotos/catalogo/uva-vale-de-rosa-sem-grainha.webp",
    uva_dona_maria: "fotos/catalogo/uva-dona-maria.webp",
    uva_vale_rosa: "fotos/catalogo/uva-vale-de-rosa-sem-grainha.webp",
    uva_vale_rosa_preta: "fotos/catalogo/uva-vale-de-rosa-preta-sem-grainha.webp",
    manga:      "fotos/catalogo/manga-aviao.webp",
    manguita:   "fotos/catalogo/manguita.webp",
    peras:      "fotos/catalogo/pera-rocha.webp",
    pera_rocha_grande: "fotos/catalogo/pera-rocha-grande.webp",
    pera_rocha_pequena: "fotos/catalogo/pera-rocha-nacional-pequena.webp",
    pera_general: "fotos/catalogo/pera-general-grande.webp",
    limoes:     "fotos/catalogo/limao.webp",
    cerejas:    "fotos/catalogo/cereja-fundao.webp",
    cereja_gardunha: "fotos/catalogo/cereja-gardunha.webp",
    kiwi:       "fotos/catalogo/kiwi-green-new-zealand.webp",
    abacate:    "fotos/catalogo/abacate-hass.webp",
    coco:       "fotos/coco.jpeg",
    ameixa:     "fotos/catalogo/ameixa.webp",
    ameixa_branca: "fotos/catalogo/ameixa-branca.webp",
    ameixa_roxa:"fotos/catalogo/ameixa-roxa-nacional.webp",
    ameixa_vermelha: "fotos/catalogo/ameixa-vermelha.webp",
    tomates:    "fotos/catalogo/tomate-salada.webp",
    cenouras:   "fotos/catalogo/cenoura.webp",
    brocoulos:  "fotos/catalogo/brocolos-sem-folha.webp",
    alface:     "fotos/catalogo/alface.webp",
    alface_roxa:"fotos/catalogo/alface-roxa.webp",
    pepino:     "fotos/catalogo/pepino.webp",
    pimentos:   "fotos/catalogo/pimento-verde.webp",
    cebolas:    "fotos/catalogo/cebola-doce.webp",
    alho:       "fotos/catalogo/alho-seco.webp",
    batatas:    "fotos/catalogo/batata-branca.webp",
    milho:      "fotos/catalogo/macaroca.webp",
    espinafres: "fotos/catalogo/espinafres.webp",
    beringela:  "fotos/catalogo/beringela.webp",
    curgete:    "fotos/catalogo/curgete.webp",
    cogumelos:  "fotos/catalogo/cogumelos.webp",
    couve:      "fotos/catalogo/couve-portuguesa.webp",
    batatadoce: "fotos/catalogo/batata-doce.webp",
    batata_doce_laranja: "fotos/catalogo/batata-doce-cor-laranja.webp",
    salsa:        "fotos/catalogo/salsa.webp",
    coentros:     "fotos/catalogo/coentros.webp",
    hortela:      "fotos/catalogo/hortela.webp",
    abobora:      "fotos/catalogo/abobora-inteira.webp",
    abobora_fatiada: "fotos/catalogo/abobora-fatiada.webp",
    alho_frances: "fotos/catalogo/alho-frances.webp",
    couveflor:    "fotos/catalogo/couve-flor.webp",
    feijao_verde: "fotos/catalogo/feijao-verde.webp",
    nabo:         "fotos/catalogo/nabo.webp",
    agriao:       "fotos/catalogo/agriao.webp",
    beterraba:    "fotos/catalogo/beterraba.webp",
    couvecoracao: "fotos/catalogo/couve-coracao.webp",
    couvelombarda:"fotos/catalogo/couve-lombarda.webp",
    grelos:       "fotos/catalogo/grelo-de-nabo.webp",
    grelo_couve:  "fotos/catalogo/grelo-de-couve.webp",
    nabica:       "fotos/catalogo/nabica.webp",
    malagueta:    "fotos/catalogo/malagueta.webp",
    quiabo:       "fotos/catalogo/quiabo.webp",
    rabanete:     "fotos/catalogo/rabanete.webp",
    xuxu:         "fotos/catalogo/chuchu.webp",
    feijao_catarino:"fotos/feijao_catarino.jpeg",
    feijao_dourado: "fotos/catalogo/feijao-dourado.webp",
    feijao_maduro:    "fotos/catalogo/feijao-maduro.webp",
    abobora_cortada:  "fotos/abobora_cortada.jpeg",
    abobora_cabocha:  "fotos/catalogo/abobora-cabocha.webp",
    abobora_butternut:"fotos/catalogo/abobora-butternut.webp",
    cebola_nova:      "fotos/catalogo/cebola-nova.webp",
    gengibre:         "fotos/catalogo/gengibre.webp",
    mandioca:         "fotos/catalogo/mandioca.webp",
    inhame:           "fotos/catalogo/inhame.webp",
    tomate_coracao_boi:"fotos/catalogo/tomate-coracao-de-boi.webp",
    lima:             "fotos/catalogo/lima.webp",
    tomate_salada:    "fotos/catalogo/tomate-salada.webp",
    tomate_cacho:     "fotos/catalogo/tomate-cacho.webp",
    tomate_chucha:    "fotos/catalogo/tomate-chucha.webp",
    tomate_cereja:    "fotos/catalogo/tomate-cereja.webp",
    tomate_rosa:      "fotos/catalogo/tomate-rosa.webp",
    pimento_verde:    "fotos/catalogo/pimento-verde.webp",
    pimento_vermelho: "fotos/catalogo/pimento-vermelho.webp",
    batata_agria:     "fotos/catalogo/batata-agria.webp",
    batata_branca:    "fotos/catalogo/batata-branca.webp",
    batata_olho_perdiz:"fotos/catalogo/batata-olho-de-perdiz.webp",
    batata_vermelha:  "fotos/catalogo/batata-vermelha.webp",
    framboesa:  "fotos/catalogo/framboesa.webp",
    mirtilos:   "fotos/catalogo/mirtilos.webp",
    amoras:     "fotos/catalogo/amoras.webp",
    lichia:     "fotos/catalogo/lichia.webp",
    alperce:    "fotos/catalogo/alperce.webp",
    diospiro:   "fotos/catalogo/diospiros-kaki.webp",
    papaia:     "fotos/catalogo/papaia.webp",
    maca_verde: "fotos/catalogo/maca-granny-smith.webp",
    pessego_amarelo:  "fotos/catalogo/pessego-amarelo-pequeno.webp",
    pessego_vermelho: "fotos/catalogo/pessego-vermelho-medio.webp",
    pessego_rosa:     "fotos/catalogo/pessego-rosa.webp",
    pessego_paraguaio:"fotos/catalogo/paraguaio.webp",
    nectarina:        "fotos/catalogo/nectarina-media.webp",
    nectarina_grande: "fotos/catalogo/nectarina-grande-premium.webp",
    banana_madeira:   "fotos/catalogo/banana-madeira.webp",
    banana_pao:       "fotos/catalogo/banana-pao.webp",
    ameixa_abrunho:   "fotos/catalogo/ameixa-abrunho-nacional.webp",
    mamao:            "fotos/catalogo/mamao.webp",
    maca_pink_lady:   "fotos/catalogo/maca-pink-lady.webp",
    maca_reineta:     "fotos/catalogo/maca-reineta.webp",
    maca_fuji:        "fotos/catalogo/maca-fuji.webp",
    maca_fuji_premium:"fotos/catalogo/maca-fuji-premium.webp",
    maca_golden:      "fotos/catalogo/maca-golden.webp",
    maca_golden_rosa: "fotos/catalogo/maca-golden-rosa.webp",
    bravo_esmolfe:    "fotos/catalogo/bravo-esmolfe-premium.webp",
    maca_gala:        "fotos/catalogo/maca-royal-gala-media.webp",
    maca_gala_pequena:"fotos/catalogo/maca-royal-gala-nacional-pequena.webp",
    marmelo:          "fotos/catalogo/marmelo.webp",
    anona:            "fotos/catalogo/anona.webp",
    castanha:         "fotos/catalogo/castanha.webp",
    laranja_africa:   "fotos/catalogo/laranja-africa-do-sul.webp",
    cabaz_detox:      "fotos/catalogo/cabaz-detox.webp",
    cabaz_frutas:  "fotos/catalogo/cabaz-frutas.webp",
    cabaz_legumes: "fotos/cabaz_legumes.jpeg",
    cabaz_mix:     "fotos/cabaz_mix.jpeg",
    cabaz_verao:   "fotos/catalogo/cabaz-verao.webp",
  };
  const SFX = "?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop";
  // Versão das imagens locais — incrementar para forçar atualização de cache no browser.
    const IMG_VER = "v=19";
  function urlFoto(u) {
    if (!u) return '';
    if (!u.startsWith('fotos/')) return u + SFX;
    return u + (u.includes('?') ? '&' : '?') + IMG_VER;
  }

  const produtos = {
    // FRUTAS — Preço por kg (exceto frutos vermelhos por cuvete e fruta pesada à unidade → venda:"estimado").
    frutas: [
      { nome:"Melancia 1/4",            emoji:"🍉", topVendido:true, venda:"estimado", pricePerKg:0.99, averageWeightKg:3, peso:"1/4 de melancia • aprox. 3 kg", preco:"0,99 €", origem:"Marrocos", foto:FOTOS.melancia, alt:"Quarto de melancia com sementes pretas em fundo branco", badge:"🌞 Verão", badgeClass:"", rel:["Morango 500g","Melão","Uva Vale de Rosa sem grainha","Hortelã"] },
      { nome:"Melancia com sementes",   emoji:"🍉", venda:"estimado", pricePerKg:0.99, averageWeightKg:3, peso:"1 unidade • aprox. 3 kg", preco:"0,99 €", foto:FOTOS.melancia_sementes, alt:"Melancia cortada com sementes pretas visíveis", badge:"🌞 Verão", badgeClass:"", rel:["Melão","Morango 500g","Abacaxi Maturado","Hortelã"] },
      { nome:"Melão",                   emoji:"🍈", topVendido:true, venda:"estimado", pricePerKg:0.99, averageWeightKg:2.5, peso:"1 unidade • aprox. 2,5 kg", preco:"0,99 €", origem:"Alentejo", foto:FOTOS.melao_branco, alt:"Melão verde nacional, pele de sapo", badge:"🌞 Verão", badgeClass:"", rel:["Morango 500g","Melancia 1/4","Uva Vale de Rosa sem grainha"] },
      { nome:"Meloa",                   emoji:"🍈", venda:"estimado", pricePerKg:2.49, averageWeightKg:1.3, peso:"1 unidade • aprox. 1,3 kg", preco:"2,49 €", origem:"Algarve", foto:FOTOS.melao_am, alt:"Meloa amarela inteira e cortada", badge:"🌞 Verão", badgeClass:"" },
      { nome:"Morango 500g",            emoji:"🍓", peso:"500 g", preco:"3,99 €", origem:"Nacional", foto:FOTOS.morangos, alt:"Morangos frescos isolados em fundo branco", badge:"🔥 Popular", badgeClass:"badge-hot", baseLinha:"Sujeito a disponibilidade", rel:["Banana Madeira","Kiwi Green New Zealand","Manga Avião","Melão"] },
      { nome:"Pêssego amarelo pequeno", emoji:"🍑", peso:"1 kg", preco:"1,99 €", origem:"Nacional", foto:FOTOS.pessego_amarelo, alt:"Pêssegos amarelos pequenos em fundo branco" },
      { nome:"Pêssego vermelho médio",  emoji:"🍑", peso:"1 kg", preco:"1,99 €", origem:"Nacional", foto:FOTOS.pessego_vermelho, alt:"Pêssego vermelho médio cortado e inteiro" },
      { nome:"Paraguaio",               emoji:"🍑", peso:"1 kg", preco:"3,59 €", origem:"Nacional", foto:FOTOS.pessego_paraguaio, alt:"Pêssego paraguaio achatado (saturn peach)" },
      { nome:"Pêssego rosa",            emoji:"🍑", peso:"1 kg", preco:"2,99 €", origem:"Nacional", foto:FOTOS.pessego_rosa, alt:"Pêssegos de polpa amarela e pele rosada" },
      { nome:"Nectarina média",         emoji:"🍑", peso:"1 kg", preco:"1,99 €", origem:"Nacional", foto:FOTOS.nectarina, alt:"Nectarina média isolada em fundo claro" },
      { nome:"Nectarina grande premium quality", emoji:"🍑", peso:"1 kg", preco:"3,49 €", origem:"Nacional", foto:FOTOS.nectarina_grande, alt:"Nectarina grande premium em fundo claro", badge:"💎 Premium", badgeClass:"" },
      { nome:"Ameixa vermelha",         emoji:"🍑", peso:"1 kg", preco:"2,49 €", origem:"Nacional", foto:FOTOS.ameixa_vermelha, alt:"Ameixas vermelhas frescas" },
      { nome:"Cereja de Fundão",        emoji:"🍒", topVendido:true, peso:"1 kg", preco:"6,99 €", status:"Indisponível",   foto:FOTOS.cerejas, alt:"Cerejas vermelhas e escuras em fundo claro", badge:"⛔ Esgotado",  badgeClass:"badge-hot" },
      { nome:"Cereja Gardunha",         emoji:"🍒", peso:"1 kg", preco:"5,99 €", status:"Indisponível", origem:"Beira",    foto:FOTOS.cereja_gardunha, alt:"Cerejas Bing vermelhas brilhantes", badge:"⛔ Esgotado" , badgeClass:"badge-hot" },
      { nome:"Uva Vale de Rosa sem grainha", emoji:"🍇", peso:"1 kg", preco:"7,99 €", origem:"Portugal", foto:FOTOS.uva_vale_rosa, alt:"Uvas vermelhas sem grainha, variedade Vale de Rosa" },
      { nome:"Figos",                   emoji:"🫐", peso:"1 kg", preco:"7,99 €",                    foto:FOTOS.figos, alt:"Figo comum cortado ao meio, polpa rosada", badge:"🌞 Verão",    badgeClass:"" },
      { nome:"Manga Avião",             emoji:"🥭", venda:"estimado", pricePerKg:5.79, averageWeightKg:0.65, peso:"1 unidade • aprox. 650 g", preco:"5,79 €", origem:"Espanha", foto:FOTOS.manga, alt:"Manga Kent de avião", badge:"🌱 Bio", badgeClass:"badge-new", rel:["Abacaxi Maturado","Mamão","Papaia","Banana Madeira"] },
      { nome:"Abacaxi Maturado",        emoji:"🍍", venda:"estimado", pricePerKg:2.99, averageWeightKg:1.8, peso:"1 unidade • aprox. 1,8 kg", preco:"2,99 €", origem:"Costa Rica", foto:FOTOS.ananas, alt:"Ananás inteiro em fundo branco", badge:"💎 Premium", badgeClass:"" },
      { nome:"Limão",                   emoji:"🍋", peso:"1 kg", preco:"1,99 €", origem:"Portugal", foto:FOTOS.limoes, alt:"Limão inteiro e cortado ao meio", badge:"🌱 Bio" , badgeClass:"badge-new"},
      { nome:"Lima",                    emoji:"🍋", peso:"1 kg", preco:"4,99 €",                   foto:FOTOS.lima, alt:"Limas verdes inteiras" },
      { nome:"Banana Del Monte",        emoji:"🍌", peso:"1 kg", preco:"1,79 €", origem:"Costa Rica", foto:FOTOS.bananas, alt:"Bananas Cavendish amarelas em fundo claro", badge:"💎 Premium",  badgeClass:"" },
      { nome:"Banana Madeira",          emoji:"🍌", peso:"1 kg", preco:"3,59 €",                    foto:FOTOS.banana_madeira, alt:"Bananas da Madeira" },
      { nome:"Banana-pão",            emoji:"🍌", peso:"1 kg", preco:"2,99 €", origem:"Angola", foto:FOTOS.banana_pao, alt:"Banana-pão (plantain) em fundo branco", badge:"🆕 Novo", badgeClass:"badge-new" },
      { nome:"Laranja Algarve",         emoji:"🍊", peso:"1 kg", preco:"1,20 €", origem:"Algarve",  status:"Indisponível", foto:FOTOS.laranja_algarve, alt:"Laranjas com folhas, aspeto de pomar" },
      { nome:"Laranja Algarve Premium", emoji:"🍊", peso:"1 kg", preco:"1,79 €", origem:"Nacional", status:"Indisponível", foto:FOTOS.laranja_algarve_premium, alt:"Laranjas no ramo com folhas", badge:"💎 Premium",  badgeClass:"" },
      { nome:"Clementina",              emoji:"🍊", peso:"1 kg", preco:"2,99 €", origem:"Nacional", foto:FOTOS.clementina, alt:"Clementinas com folhas em ramo" },
      { nome:"Tangerina",               emoji:"🍊", peso:"1 kg", preco:"2,99 €",                    foto:FOTOS.tangerina, alt:"Tangerinas mandarinas frescas" },
      { nome:"Pêra Rocha",              emoji:"🍐", peso:"1 kg", preco:"1,99 €", origem:"Oeste",    foto:FOTOS.peras, alt:"Pêra Rocha do Oeste, vista do cálice" },
      { nome:"Pêra Rocha grande",       emoji:"🍐", peso:"1 kg", preco:"2,99 €", origem:"Nacional", foto:FOTOS.pera_rocha_grande, alt:"Pêra Rocha grande em fundo branco", badge:"💎 Premium",  badgeClass:"" },
      { nome:"Pêra Rocha nacional pequena", emoji:"🍐", peso:"1 kg", promo:true, precoNormal:"1,99 €", preco:"0,79 €", origem:"Nacional", foto:FOTOS.pera_rocha_pequena, alt:"Pêra Rocha nacional pequena", badge:"🏷️ Promoção", badgeClass:"badge-hot" },
      { nome:"Pêra General grande",     emoji:"🍐", peso:"1 kg", preco:"2,99 €",                    foto:FOTOS.pera_general, alt:"Peras grandes da variedade General" },
      { nome:"Kiwi Green New Zealand",  emoji:"🥝", peso:"1 kg", preco:"5,99 €", origem:"Nova Zelândia", foto:FOTOS.kiwi, alt:"Kiwi verde da Nova Zelândia, inteiro e cortado" },
      { nome:"Abacate Hass",            emoji:"🥑", peso:"1 kg", preco:"5,99 €",                    foto:FOTOS.abacate, alt:"Abacate Hass inteiro e cortado ao meio", badge:"💎 Premium",  badgeClass:"" },
      { nome:"Lichia",                  emoji:"🔴", peso:"1 kg", preco:"5,99 €", status:"Indisponível", foto:FOTOS.lichia, alt:"Lichias com casca e semente", badge:"💎 Premium",  badgeClass:"" },
      { nome:"Ameixa Roxa Nacional",    emoji:"🟣", topVendido:true, peso:"1 kg", promo:true, precoNormal:"1,99 €", preco:"0,99 €", origem:"Nacional", foto:FOTOS.ameixa_roxa, alt:"Ameixas roxas nacionais", badge:"🏷️ Promoção", badgeClass:"badge-hot" },
      { nome:"Ameixa Branca Nacional",  emoji:"🟡", peso:"1 kg", preco:"1,49 €", origem:"Nacional", status:"Indisponível", foto:FOTOS.ameixa_branca, alt:"Ameixas amarelas ou brancas" },
      { nome:"Ameixa Abrunho nacional", emoji:"🟣", peso:"1 kg", preco:"2,99 €",                    foto:FOTOS.ameixa_abrunho, alt:"Ameixa abrunho nacional (tipo damasco-ameixa)", badge:"👌 Recomendado", badgeClass:"badge-new" },
      { nome:"Alperce Nacional",        emoji:"🍑", peso:"1 kg", preco:"2,99 €", origem:"Nacional", status:"Indisponível", foto:FOTOS.alperce, alt:"Alperces nacionais inteiros" },
      { nome:"Diospiros / Kaki",        emoji:"🟠", peso:"1 kg", preco:"3,99 €", origem:"Nacional", foto:FOTOS.diospiro, alt:"Diospiro kaki inteiro e cortado em fundo branco" },
      { nome:"Mamão",                   emoji:"🥭", venda:"estimado", pricePerKg:4.79, averageWeightKg:0.9, peso:"1 unidade • aprox. 900 g", preco:"4,79 €", foto:FOTOS.mamao, alt:"Mamão / papaia cortado ao meio com sementes", rel:["Manga Avião","Papaia","Abacaxi Maturado"] },
      { nome:"Papaia",                  emoji:"🥭", venda:"estimado", pricePerKg:5.49, averageWeightKg:0.45, peso:"1 unidade • aprox. 450 g", preco:"5,49 €", foto:FOTOS.papaia, alt:"Metade de papaia madura", rel:["Manga Avião","Mamão","Abacaxi Maturado"] },
      { nome:"Romã",                    emoji:"🔴", peso:"1 kg", preco:"3,99 €",                    foto:FOTOS.roma, alt:"Romã inteira em fundo branco" },
      { nome:"Maçã Pink Lady",          emoji:"🍎", peso:"1 kg", preco:"3,99 €",                    foto:FOTOS.maca_pink_lady, alt:"Maçãs Pink Lady vermelhas" },
      { nome:"Maçã Granny Smith",       emoji:"🍏", peso:"1 kg", preco:"2,99 €",                    foto:FOTOS.maca_verde, alt:"Maçã Granny Smith verde" },
      { nome:"Maçã Golden",             emoji:"🍎", peso:"1 kg", preco:"1,59 €",                    foto:FOTOS.maca_golden, alt:"Maçãs Golden Delicious" },
      { nome:"Maçã Reineta",            emoji:"🍏", peso:"1 kg", preco:"3,59 €",                    foto:FOTOS.maca_reineta, alt:"Maçã Reineta de casca rústica" },
      { nome:"Bravo Esmolfe premium",   emoji:"🍎", peso:"1 kg", preco:"3,99 €", origem:"Nacional", foto:FOTOS.bravo_esmolfe, alt:"Maçã Bravo de Esmolfe — foto da loja em breve", badge:"💎 Premium", badgeClass:"" },
      { nome:"Maçã Fuji",               emoji:"🍎", peso:"1 kg", preco:"1,89 €",                    foto:FOTOS.maca_fuji, alt:"Maçã Fuji" },
      { nome:"Maçã Fuji Premium",       emoji:"🍎", peso:"1 kg", preco:"2,99 €",                    foto:FOTOS.maca_fuji_premium, alt:"Maçãs Fuji com gotas de água", badge:"💎 Premium",  badgeClass:"" },
      { nome:"Maçã Royal Gala média",   emoji:"🍎", peso:"1 kg", preco:"1,69 €",                    foto:FOTOS.maca_gala, alt:"Maçãs Royal Gala de calibre médio" },
      { nome:"Maçã Golden Rosa Francesa",emoji:"🍎",peso:"1 kg", preco:"4,99 €", status:"Indisponível", foto:FOTOS.maca_golden_rosa, alt:"Maçã Golden rosa francesa", badge:"💎 Premium",  badgeClass:"" },
      { nome:"Abacaxi Avião Costa Rica",emoji:"🍍", venda:"estimado", pricePerKg:6.49, averageWeightKg:2.5, peso:"1 unidade • aprox. 2,5 kg", preco:"6,49 €", origem:"Costa Rica", foto:FOTOS.abacaxi_aviao, alt:"Ananás de avião da Costa Rica em fundo branco", badge:"💎 Premium", badgeClass:"" },
      { nome:"Framboesa",               emoji:"🍒", peso:"Cuvete 130 g", preco:"2,29 €",            foto:FOTOS.framboesa, alt:"Framboesa isolada", badge:"🌞 Verão",    badgeClass:"" },
      { nome:"Mirtilos",                emoji:"🫐", peso:"Cuvete 125 g", preco:"2,49 €",            foto:FOTOS.mirtilos, alt:"Mirtilos frescos", badge:"🌞 Verão",    badgeClass:"" },
      { nome:"Amoras",                  emoji:"🫐", peso:"Cuvete 150 g", preco:"2,99 €",            foto:FOTOS.amoras, alt:"Amoras silvestres", badge:"🌞 Verão",    badgeClass:"" },
      { nome:"Uva Dona Maria",          emoji:"🍇", peso:"1 kg", preco:"2,99 €", origem:"Portugal", foto:FOTOS.uva_dona_maria, alt:"Cacho de uvas verdes Dona Maria em fundo branco" },
      { nome:"Uva Vale de Rosa preta sem grainha", emoji:"🍇", peso:"1 kg", preco:P, origem:"Portugal", foto:FOTOS.uva_vale_rosa_preta, alt:"Uvas pretas sem grainha, variedade Vale de Rosa" },
      { nome:"Laranja África do Sul premium quality", emoji:"🍊", peso:"1 kg", preco:"1,99 €", origem:"África do Sul", foto:FOTOS.laranja_africa, alt:"Laranja da África do Sul cortada em fundo branco", badge:"💎 Premium", badgeClass:"" },
      { nome:"Manguita",                emoji:"🥭", peso:"1 kg", preco:"5,99 €",                    foto:FOTOS.manguita, alt:"Manguita amarela pequena, tipo Nam Dok Mai" },
      { nome:"Marmelo",                 emoji:"🍐", peso:"1 kg", preco:"2,49 €",                    foto:FOTOS.marmelo, alt:"Marmelo variedade Portugal no ramo" },
      { nome:"Anona",                   emoji:"🍏", peso:"1 kg", preco:"3,99 €",                    foto:FOTOS.anona, alt:"Anona (fruta-pinha) em fundo branco" },
      { nome:"Castanha",                emoji:"🌰", peso:"1 kg", preco:"5,99 €",                    foto:FOTOS.castanha, alt:"Castanhas doce (Castanea sativa) no ouriço" },
      { nome:"Maçã Royal Gala nacional pequena", emoji:"🍎", peso:"1 kg", preco:"0,79 €", origem:"Nacional", foto:FOTOS.maca_gala_pequena, alt:"Maçã Royal Gala nacional de calibre pequeno" },
      { nome:"Ameixa",                  emoji:"🍑", peso:"1 kg", preco:"2,99 €",                    foto:FOTOS.ameixa, alt:"Ameixas frescas" },
    ],
    // LEGUMES — ordem alfabética. Preço por kg; ervas/grelos por molho; couves à unidade.
    legumes: [
      { nome:"Abóbora Butternut",      emoji:"🎃", venda:"estimado", pricePerKg:1.49, averageWeightKg:1.2, peso:"1 unidade • aprox. 1,2 kg", preco:"1,49 €", foto:FOTOS.abobora_butternut, badge:null },
      { nome:"Abóbora Cabocha",        emoji:"🎃", peso:"1 kg",       preco:"3,49 €", foto:FOTOS.abobora_cabocha,   badge:null },
      { nome:"Abóbora Fatiada s/ Caroço",emoji:"🎃", peso:"1 kg",     preco:"1,89 €", foto:FOTOS.abobora_fatiada,   badge:null },
      { nome:"Abóbora Inteira",        emoji:"🎃", venda:"estimado", pricePerKg:1.20, averageWeightKg:8, weightRange:"7–9 kg", peso:"1 unidade • aprox. 7–9 kg", preco:"1,20 €", foto:FOTOS.abobora, badge:null },
      { nome:"Agrião",                 emoji:"🌿", peso:"Molho",      preco:"1,50 €", foto:FOTOS.agriao,           badge:null },
      { nome:"Alface",                 emoji:"🥬", venda:"unidade", peso:"1 unidade • aprox. 800 g", preco:"2,49 €", foto:FOTOS.alface, badge:null, rel:["Tomate Salada","Pepino","Cenoura"] },
      { nome:"Alface Roxa",            emoji:"🥬", peso:"1 un",       preco:"1,60 €", foto:FOTOS.alface_roxa,      badge:null },
      { nome:"Alho Francês",           emoji:"🥬", peso:"500 g",      preco:"1,25 €", foto:FOTOS.alho_frances,     badge:null },
      { nome:"Alho Seco",              emoji:"🧄", peso:"250 g",      preco:"1,65 €", foto:FOTOS.alho,             badge:null },
      { nome:"Batata Agria",           emoji:"🥔", peso:"1 kg",       preco:"0,99 €", foto:FOTOS.batata_agria,      badge:null },
      { nome:"Batata Branca",          emoji:"🥔", peso:"1 kg",       preco:"0,99 €", foto:FOTOS.batata_branca,     badge:null },
      { nome:"Batata Doce",            emoji:"🍠", peso:"1 kg",       preco:"2,49 €", foto:FOTOS.batatadoce,       badge:null },
      { nome:"Batata Doce Cor Laranja",emoji:"🍠", peso:"1 kg",       preco:"2,49 €", foto:FOTOS.batata_doce_laranja, badge:null },
      { nome:"Batata Olho de Perdiz",  emoji:"🥔", peso:"1 kg",       preco:"1,79 €", foto:FOTOS.batata_olho_perdiz,badge:null },
      { nome:"Batata Vermelha",        emoji:"🥔", peso:"1 kg",       preco:"0,99 €", foto:FOTOS.batata_vermelha,   badge:null },
      { nome:"Beringela",              emoji:"🍆", peso:"1 kg",       preco:"2,99 €", foto:FOTOS.beringela,        badge:null },
      { nome:"Beterraba",              emoji:"🟣", peso:"1 kg",       preco:"1,69 €", foto:FOTOS.beterraba,        badge:null },
      { nome:"Brócolos sem Folha",     emoji:"🥦", venda:"unidade", peso:"1 unidade • aprox. 500 g", preco:"1,50 €", baseLinha:"Base: 2,99 €/kg", foto:FOTOS.brocoulos, badge:"🌱 Bio", badgeClass:"badge-bio" },
      { nome:"Cebola Doce",            emoji:"🧅", peso:"1 kg",       preco:"2,49 €", foto:FOTOS.cebolas,          badge:null },
      { nome:"Cebola Nova",            emoji:"🧅", peso:"1 kg",       preco:"1,20 €", foto:FOTOS.cebola_nova,      badge:null },
      { nome:"Cenoura",                emoji:"🥕", peso:"1 kg",       preco:"0,99 €", foto:FOTOS.cenouras,         badge:null },
      { nome:"Chuchu",                 emoji:"🥒", venda:"estimado", pricePerKg:3.49, averageWeightKg:0.4, peso:"1 unidade • aprox. 400 g", preco:"3,49 €", foto:FOTOS.xuxu, badge:null },
      { nome:"Coentros",               emoji:"🌿", topVendido:true, peso:"Molho 100g", preco:"1,20 €", foto:FOTOS.coentros, badge:null, rel:["Salsa","Hortelã","Tomate Salada","Cebola Doce"] },
      { nome:"Cogumelos",              emoji:"🍄", peso:"500 g",      preco:"2,99 €", foto:FOTOS.cogumelos,        badge:null },
      { nome:"Couve Coração",          emoji:"🥬", venda:"unidade", peso:"1 unidade • aprox. 1 kg", preco:"1,39 €", foto:FOTOS.couvecoracao, badge:null },
      { nome:"Couve Lombarda",         emoji:"🥬", venda:"estimado", pricePerKg:1.59, averageWeightKg:1.2, peso:"1 unidade • aprox. 1,2 kg", preco:"1,59 €", foto:FOTOS.couvelombarda, badge:null },
      { nome:"Couve Portuguesa",       emoji:"🥬", peso:"1 un",       preco:"1,99 €", foto:FOTOS.couve,            badge:null },
      { nome:"Couve-flor",             emoji:"🥦", venda:"unidade", peso:"1 unidade • aprox. 700 g", preco:"2,99 €", baseLinha:"Base: 2,99 €/kg", foto:FOTOS.couveflor, badge:"🌱 Bio" , badgeClass:"badge-new"},
      { nome:"Curgete",                emoji:"🥒", origem:"Portugal", peso:"1 kg",       preco:"2,49 €", foto:FOTOS.curgete,          badge:"🌱 Bio" , badgeClass:"badge-new"},
      { nome:"Espinafres",             emoji:"🥬", peso:"Molho",      preco:"2,49 €", foto:FOTOS.espinafres,       badge:"🌱 Bio",  badgeClass:"badge-bio" },
      { nome:"Feijão Dourado",         emoji:"🫘", peso:"500 g",      preco:"4,99 €", foto:FOTOS.feijao_dourado,   badge:null },
      { nome:"Feijão Maduro",          emoji:"🫘", peso:"1 kg",       preco:"4,99 €", foto:FOTOS.feijao_maduro,    badge:null },
      { nome:"Feijão Verde",           emoji:"🫛", peso:"1 kg",       preco:"4,99 €", foto:FOTOS.feijao_verde,     badge:null },
      { nome:"Gengibre",               emoji:"🫚", peso:"250 g",      preco:"1,50 €", foto:FOTOS.gengibre,         badge:null },
      { nome:"Grelo de Couve",         emoji:"🌿", peso:"Molho",      preco:"3,50 €", foto:FOTOS.grelo_couve,      badge:null },
      { nome:"Grelo de Nabo",          emoji:"🌿", peso:"Molho",      preco:"3,95 €", foto:FOTOS.grelos,           badge:null },
      { nome:"Hortelã",                emoji:"🌿", peso:"100 g",      preco:"1,20 €", foto:FOTOS.hortela,          badge:null, rel:["Salsa","Coentros"] },
      { nome:"Inhame",                 emoji:"🍠", peso:"1 kg",       preco:"6,99 €", foto:FOTOS.inhame,           badge:null },
      { nome:"Maçaroca",               emoji:"🌽", peso:"1 un",       preco:"2,99 €", foto:FOTOS.milho,            badge:null },
      { nome:"Malagueta",              emoji:"🌶️", peso:"250 g",      preco:"2,95 €", foto:FOTOS.malagueta,        badge:null },
      { nome:"Mandioca",               emoji:"🥔", peso:"1 kg",       preco:"4,99 €", foto:FOTOS.mandioca,         badge:null },
      { nome:"Nabiça",                 emoji:"🌿", peso:"Molho",      preco:"2,49 €", foto:FOTOS.nabica,           badge:null },
      { nome:"Nabo",                   emoji:"🥬", peso:"1 kg",       preco:"2,49 €", foto:FOTOS.nabo,             badge:null },
      { nome:"Pepino",                 emoji:"🥒", origem:"Portugal", peso:"1 kg",       preco:"2,49 €", foto:FOTOS.pepino,           badge:"🌱 Bio", rel:["Tomate Salada","Alface","Cenoura"] , badgeClass:"badge-new"},
      { nome:"Pimento Verde",          emoji:"🫑", peso:"500 g",      preco:"1,99 €", foto:FOTOS.pimento_verde,     badge:null },
      { nome:"Pimento Vermelho",       emoji:"🫑", peso:"500 g",      preco:"1,99 €", foto:FOTOS.pimento_vermelho,  badge:null },
      { nome:"Quiabo",                 emoji:"🫛", peso:"1 kg",      preco:"6,99 €", foto:FOTOS.quiabo,           badge:null },
      { nome:"Rabanete",               emoji:"🔴", peso:"500 g",      preco:"1,99 €", foto:FOTOS.rabanete,         badge:null },
      { nome:"Salsa",                  emoji:"🌿", peso:"Molho 100g", preco:"1,00 €", foto:FOTOS.salsa,            badge:null },
      { nome:"Tomate Cacho",           emoji:"🍅", peso:"1 kg",       preco:"2,99 €", foto:FOTOS.tomate_cacho,      badge:null },
      { nome:"Tomate Cereja",          emoji:"🍅", peso:"500 g",      preco:"2,50 €", foto:FOTOS.tomate_cereja,     badge:null },
      { nome:"Tomate Chucha",          emoji:"🍅", peso:"1 kg",       preco:"1,99 €", foto:FOTOS.tomate_chucha,     badge:null },
      { nome:"Tomate Coração de Boi",  emoji:"🍅", peso:"1 kg",       preco:"2,99 €", foto:FOTOS.tomate_coracao_boi,badge:null },
      { nome:"Tomate Rosa",            emoji:"🍅", peso:"1 kg",       preco:"2,99 €", foto:FOTOS.tomate_rosa,      badge:"💎 Premium", badgeClass:"" },
      { nome:"Tomate Salada",          emoji:"🍅", peso:"1 kg",       preco:"1,99 €", foto:FOTOS.tomate_salada,     badge:"🌱 Bio", badgeClass:"badge-new", rel:["Alface","Pepino","Cebola Doce","Coentros"] },
    ],
    // CABAZES — cestos prontos de frutas e/ou legumes.
    cabazes: [
      { nome:"Cabaz Detox",        emoji:"🥗", peso:"≈ 12 kg", preco:"39,50 €", foto:FOTOS.cabaz_detox, badge:"💚 Detox", badgeClass:"badge-bio",
        nota:"A imagem desta cabaz é meramente ilustrativa.",
        itens: [
          { grupo:"Frutas", q:"1 un",   nome:"Ananás" },
          {                 q:"1 kg",   nome:"Laranja" },
          {                 q:"500 g",  nome:"Limão" },
          {                 q:"500 g",  nome:"Kiwi" },
          {                 q:"1 kg",   nome:"Abacate" },
          {                 q:"1 kg",   nome:"Clementina" },
          {                 q:"1 kg",   nome:"Maçã Starking" },
          {                 q:"1 un",   nome:"Manga" },
          { grupo:"Legumes",q:"500 g",  nome:"Espinafres" },
          {                 q:"750 g",  nome:"Beterraba" },
          {                 q:"1 un",   nome:"Couve Coração" },
          {                 q:"1 un",   nome:"Alface" },
          {                 q:"1 kg",   nome:"Cenoura" },
          {                 q:"500 g",  nome:"Pepino" },
          {                 q:"700 g",  nome:"Curgete" },
          {                 q:"150 g",  nome:"Hortelã" },
        ] },
      { nome:"Cabaz Familiar",     emoji:"🧺", peso:"≈ 11,4 kg", preco:"35,95 €", foto:FOTOS.cabaz_frutas, badge:"👪 Família", badgeClass:"badge-new",
        nota:"A imagem desta cabaz é meramente ilustrativa.",
        itens: [
          { grupo:"Frutas", q:"500 g", nome:"Pêra Rocha" },
          {                 q:"1 kg",  nome:"Banana" },
          {                 q:"1 kg",  nome:"Laranja" },
          {                 q:"1 kg",  nome:"Maçã Royal Gala" },
          { grupo:"Legumes",q:"1 pç",  nome:"Alho Francês" },
          {                 q:"500 g", nome:"Tomate Salada" },
          {                 q:"1 kg",  nome:"Couve Lombarda" },
          {                 q:"1 pç",  nome:"Alface" },
          {                 q:"500 g", nome:"Cenoura" },
          {                 q:"500 g", nome:"Cebola" },
          {                 q:"1 kg",  nome:"Batata Vermelha" },
          {                 q:"700 g", nome:"Curgete" },
        ] },
      { nome:"Cabaz de Verão",     emoji:"🍉", peso:"Frutos da época", preco:"39,95 €", foto:FOTOS.cabaz_verao, badge:"🌞 Verão", badgeClass:"",
        nota:"A imagem desta cabaz é meramente ilustrativa.",
        itens: [
          { grupo:"Frutas", q:"1 un",   nome:"Melão" },
          {                 q:"1 un",   nome:"Melancia" },
          {                 q:"1 un",   nome:"Abacaxi" },
          {                 q:"1 un",   nome:"Manga" },
          {                 q:"1 un",   nome:"Papaya" },
          {                 q:"500 g",  nome:"Pêssego" },
          {                 q:"500 g",  nome:"Ameixas" },
          {                 q:"500 g",  nome:"Alperce" },
          {                 q:"125 g",  nome:"Mirtilo" },
          {                 q:"125 g",  nome:"Framboesas" },
          {                 q:"1 kg",   nome:"Banana" },
          {                 q:"1 kg",   nome:"Laranja" },
          {                 q:"1 kg",   nome:"Maçã" },
        ] },
      { nome:"Cabaz de Legumes",   emoji:"🥦", peso:"≈ 11,8 kg", preco:"34,95 €", foto:FOTOS.cabaz_legumes, badge:null,
        nota:"A imagem desta cabaz é meramente ilustrativa.",
        itens: [
          { grupo:"Legumes", q:"500 g", nome:"Pepino" },
          {                  q:"2 un",  nome:"Pimento Verde" },
          {                  q:"2 un",  nome:"Pimento Vermelho" },
          {                  q:"500 g", nome:"Tomate" },
          {                  q:"2 un",  nome:"Curgete" },
          {                  q:"1 un",  nome:"Couve Lombarda" },
          {                  q:"300 g", nome:"Alface" },
          {                  q:"1 kg",  nome:"Cenoura" },
          {                  q:"400 g", nome:"Alho Francês" },
          {                  q:"250 g", nome:"Alho Seco" },
          {                  q:"500 g", nome:"Cebola" },
          {                  q:"2 kg",  nome:"Batata Vermelha" },
          {                  q:"500 g", nome:"Feijão Verde" },
          {                  q:"500 g", nome:"Brócolos" },
          {                  q:"300 g", nome:"Cogumelos Brancos" },
        ] },
    ],
  };

  /* ═══════════════════════════════════════════════════════════
     PROMOÇÃO PRIMEIRA COMPRA — cupão de boas-vindas.
     NOTA: A validação real (1 uso por cliente) exige o backend
     (ver docs/BACKEND-SETUP.md). Esta versão frontend é indicativa.
     ═══════════════════════════════════════════════════════════ */
  const cupaoConfig = {
    codigo: "MUNDI10",
    desconto: 10,      // € abatidos
    minimo: 40,        // € mínimo de compra
    validadeDias: 30,  // dias após emissão
    copyTitulo: "Bem-vindo à Mundi Fruta",
    copyTexto: "Receba 10€ de desconto na sua primeira compra de 40€ ou mais.",
    copyExclusivo: "Oferta exclusiva para novos clientes.",
  };

  /* ═══════════════════════════════════════════════════════════
     EQUIPA (Quem Somos) — PLACEHOLDERS.
     Substituir por nomes, funções, fotos e mensagens reais.
     Fotos reais podem ser colocadas em fotos/equipa/ e referenciadas aqui.
     ═══════════════════════════════════════════════════════════ */
  const equipa = [
    { nome:"[Nome do Proprietário]", funcao:"Proprietário", mensagem:"Escolho pessoalmente a fruta e os legumes todas as manhãs.", foto:"" },
    { nome:"[Nome]",                 funcao:"Atendimento",  mensagem:"Ajudo cada cliente a levar o melhor do dia.",              foto:"" },
    { nome:"[Nome]",                 funcao:"Loja",         mensagem:"Mantenho tudo fresco, limpo e bem apresentado.",           foto:"" },
  ];

  /* ═══════════════════════════════════════════════════════════
     AVALIAÇÕES — nota real do Google Business (4,9 ★ · 107 avaliações).
     Os textos abaixo são reais (Google). Manter em português.
     ═══════════════════════════════════════════════════════════ */
  const avaliacoesInfo = {
    nota: "4,9",
    total: 107,
    link: "https://maps.app.goo.gl/1gHGqMac4ahTtfxf8?g_st=ac",
    temas: ["Frescura", "Qualidade da fruta", "Limpeza", "Variedade", "Simpatia"],
  };

  const avaliacoes = [
    { nome:"Ana Pinto", estrelas:5, texto:"Legumes e fruta com boa qualidade. Atendimento adequado e preocupação no atendimento. Preços justos para a qualidade existente. Limpeza do espaço. Cuidado na apresentação dos artigos." },
    { nome:"Pedro Martins", estrelas:5, texto:"Boa fruta, variada e a bom preço! Gosto especialmente das promoções que fazem em fruta já muito madura, com a dupla vantagem de evitar que esta vá parar ao lixo e pagando menos! Funcionários muito simpáticos e atenciosos! Localização central." },
    { nome:"Eugene Nevezhin", estrelas:5, texto:"Very good and fresh fruits and vegetables. Affordable prices." },
  ];
